name:
    mobie
channels:
    - conda-forge
    - cpape
dependencies:
    - cluster_tools >=0.3.4
    - elf >=0.2.4
    - jsonschema
    - numba <=0.50
    - pandas
    - paintera_tools >=0.2.1
    - pip
    - requests
    - pybdv >=0.5
    - s3fs
